name: flick
description: "A safe, fast batch file renamer powered by Bridra."
publish_to: 'none'
version: 0.3.0+4

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  bridra_flutter: "^0.11.0"
  desktop_drop: ^0.7.1
  file_selector: ^1.1.0
  package_info_plus: ^10.2.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  file_selector_platform_interface: ^2.7.0
  flutter_lints: ^6.0.0
  shared_preferences_platform_interface: ^2.4.2

flutter:
  uses-material-design: true
