// Code generated by `bridra generate` from schema/bridra.json. DO NOT EDIT.

package contracts

const (
	RouteGroupSystem = "system"
	RouteGroupFiles  = "files"
	RouteGroupRename = "rename"

	MethodSystemHealth       = "system.health"
	RouteActionSystemHealth  = "health"
	MethodFilesScan          = "files.scan"
	RouteActionFilesScan     = "scan"
	MethodRenamePreview      = "rename.preview"
	RouteActionRenamePreview = "preview"
	MethodRenameApply        = "rename.apply"
	RouteActionRenameApply   = "apply"
	MethodRenameUndo         = "rename.undo"
	RouteActionRenameUndo    = "undo"
	MethodRenameHistory      = "rename.history"
	RouteActionRenameHistory = "history"
)
