// Code generated by `bridra generate` from schema/bridra.json. DO NOT EDIT.

package responses

type HealthResponse struct {
	Status           string `json:"status"`
	FrameworkVersion string `json:"frameworkVersion"`
	ProtocolVersion  int    `json:"protocolVersion"`
	Runtime          string `json:"runtime"`
	Architecture     string `json:"architecture"`
}

type ScanDirectoriesResponse struct {
	Paths        []string `json:"paths"`
	SkippedCount int      `json:"skippedCount"`
}

type RenamePlanResponse struct {
	PlanId            string   `json:"planId"`
	SourcePaths       []string `json:"sourcePaths"`
	OriginalNames     []string `json:"originalNames"`
	ProposedNames     []string `json:"proposedNames"`
	TargetPaths       []string `json:"targetPaths"`
	Statuses          []string `json:"statuses"`
	Messages          []string `json:"messages"`
	Included          []bool   `json:"included"`
	Overridden        []bool   `json:"overridden"`
	CollisionResolved []bool   `json:"collisionResolved"`
	Sizes             []int    `json:"sizes"`
	ModifiedAt        []int    `json:"modifiedAt"`
	RenameableCount   int      `json:"renameableCount"`
	UnchangedCount    int      `json:"unchangedCount"`
	ErrorCount        int      `json:"errorCount"`
	ExcludedCount     int      `json:"excludedCount"`
}

type ApplyRenameResponse struct {
	BatchId      string `json:"batchId"`
	ChangedCount int    `json:"changedCount"`
	Message      string `json:"message"`
}

type UndoRenameResponse struct {
	BatchId      string `json:"batchId"`
	ChangedCount int    `json:"changedCount"`
	Message      string `json:"message"`
}

type RenameHistoryResponse struct {
	BatchIds      []string `json:"batchIds"`
	Timestamps    []string `json:"timestamps"`
	ChangedCounts []int    `json:"changedCounts"`
	Undoable      []bool   `json:"undoable"`
}
