// Code generated by `bridra generate` from schema/bridra.json. DO NOT EDIT.

package requests

import (
	"github.com/cluion/bridra/backend/framework"
)

type ScanDirectoriesRequest struct {
	Directories   []string `json:"directories"`
	Recursive     bool     `json:"recursive"`
	Patterns      []string `json:"patterns"`
	IncludeHidden bool     `json:"includeHidden"`
}

func (ScanDirectoriesRequest) ValidatePayload(payload []byte) error {
	return framework.ValidateRequestPayload[ScanDirectoriesRequest](payload)
}

type PreviewOrganizationRequest struct {
	RootPath             string   `json:"rootPath"`
	FolderIds            []string `json:"folderIds"`
	FolderNames          []string `json:"folderNames"`
	ItemIds              []string `json:"itemIds"`
	SourcePaths          []string `json:"sourcePaths"`
	DestinationFolderIds []string `json:"destinationFolderIds"`
	CollisionStrategy    string   `json:"collisionStrategy"`
}

func (PreviewOrganizationRequest) ValidatePayload(payload []byte) error {
	return framework.ValidateRequestPayload[PreviewOrganizationRequest](payload)
}

var previewOrganizationRequestRules = framework.NewRuleRegistry[PreviewOrganizationRequest](
	framework.ForField(
		"rootPath",
		func(request PreviewOrganizationRequest) string { return request.RootPath },
		framework.MinLength(1, "RootPath must be at least 1 character."),
	),
)

func (request PreviewOrganizationRequest) Validate() error {
	return previewOrganizationRequestRules.Validate(request)
}

type ApplyOrganizationRequest struct {
	PlanId string `json:"planId"`
}

func (ApplyOrganizationRequest) ValidatePayload(payload []byte) error {
	return framework.ValidateRequestPayload[ApplyOrganizationRequest](payload)
}

var applyOrganizationRequestRules = framework.NewRuleRegistry[ApplyOrganizationRequest](
	framework.ForField(
		"planId",
		func(request ApplyOrganizationRequest) string { return request.PlanId },
		framework.MinLength(1, "PlanId must be at least 1 character."),
	),
)

func (request ApplyOrganizationRequest) Validate() error {
	return applyOrganizationRequestRules.Validate(request)
}

type UndoOrganizationRequest struct {
	BatchId string `json:"batchId"`
}

func (UndoOrganizationRequest) ValidatePayload(payload []byte) error {
	return framework.ValidateRequestPayload[UndoOrganizationRequest](payload)
}

var undoOrganizationRequestRules = framework.NewRuleRegistry[UndoOrganizationRequest](
	framework.ForField(
		"batchId",
		func(request UndoOrganizationRequest) string { return request.BatchId },
		framework.MinLength(1, "BatchId must be at least 1 character."),
	),
)

func (request UndoOrganizationRequest) Validate() error {
	return undoOrganizationRequestRules.Validate(request)
}

type PreviewRenameRequest struct {
	Paths             []string `json:"paths"`
	Recipe            string   `json:"recipe"`
	CollisionStrategy string   `json:"collisionStrategy"`
	ExcludedPaths     []string `json:"excludedPaths"`
	OverridePaths     []string `json:"overridePaths"`
	OverrideNames     []string `json:"overrideNames"`
}

func (PreviewRenameRequest) ValidatePayload(payload []byte) error {
	return framework.ValidateRequestPayload[PreviewRenameRequest](payload)
}

var previewRenameRequestRules = framework.NewRuleRegistry[PreviewRenameRequest](
	framework.ForField(
		"recipe",
		func(request PreviewRenameRequest) string { return request.Recipe },
		framework.MinLength(2, "Recipe must be at least 2 characters."),
	),
)

func (request PreviewRenameRequest) Validate() error {
	return previewRenameRequestRules.Validate(request)
}

type ApplyRenameRequest struct {
	PlanId string `json:"planId"`
}

func (ApplyRenameRequest) ValidatePayload(payload []byte) error {
	return framework.ValidateRequestPayload[ApplyRenameRequest](payload)
}

var applyRenameRequestRules = framework.NewRuleRegistry[ApplyRenameRequest](
	framework.ForField(
		"planId",
		func(request ApplyRenameRequest) string { return request.PlanId },
		framework.MinLength(1, "PlanId must be at least 1 character."),
	),
)

func (request ApplyRenameRequest) Validate() error {
	return applyRenameRequestRules.Validate(request)
}

type UndoRenameRequest struct {
	BatchId string `json:"batchId"`
}

func (UndoRenameRequest) ValidatePayload(payload []byte) error {
	return framework.ValidateRequestPayload[UndoRenameRequest](payload)
}

var undoRenameRequestRules = framework.NewRuleRegistry[UndoRenameRequest](
	framework.ForField(
		"batchId",
		func(request UndoRenameRequest) string { return request.BatchId },
		framework.MinLength(1, "BatchId must be at least 1 character."),
	),
)

func (request UndoRenameRequest) Validate() error {
	return undoRenameRequestRules.Validate(request)
}
