// Code generated by `bridra generate` from schema/bridra.json. DO NOT EDIT.

package requests

import (
	"github.com/cluion/bridra/backend/framework"
)

type ScanDirectoriesRequest struct {
	Directories   []string `json:"directories"`
	Recursive     bool     `json:"recursive"`
	Patterns      []string `json:"patterns"`
	IncludeHidden bool     `json:"includeHidden"`
}

func (ScanDirectoriesRequest) ValidatePayload(payload []byte) error {
	return framework.ValidateRequestPayload[ScanDirectoriesRequest](payload)
}

type PreviewRenameRequest struct {
	Paths         []string `json:"paths"`
	Recipe        string   `json:"recipe"`
	ExcludedPaths []string `json:"excludedPaths"`
	OverridePaths []string `json:"overridePaths"`
	OverrideNames []string `json:"overrideNames"`
}

func (PreviewRenameRequest) ValidatePayload(payload []byte) error {
	return framework.ValidateRequestPayload[PreviewRenameRequest](payload)
}

var previewRenameRequestRules = framework.NewRuleRegistry[PreviewRenameRequest](
	framework.ForField(
		"recipe",
		func(request PreviewRenameRequest) string { return request.Recipe },
		framework.MinLength(2, "Recipe must be at least 2 characters."),
	),
)

func (request PreviewRenameRequest) Validate() error {
	return previewRenameRequestRules.Validate(request)
}

type ApplyRenameRequest struct {
	PlanId string `json:"planId"`
}

func (ApplyRenameRequest) ValidatePayload(payload []byte) error {
	return framework.ValidateRequestPayload[ApplyRenameRequest](payload)
}

var applyRenameRequestRules = framework.NewRuleRegistry[ApplyRenameRequest](
	framework.ForField(
		"planId",
		func(request ApplyRenameRequest) string { return request.PlanId },
		framework.MinLength(1, "PlanId must be at least 1 character."),
	),
)

func (request ApplyRenameRequest) Validate() error {
	return applyRenameRequestRules.Validate(request)
}

type UndoRenameRequest struct {
	BatchId string `json:"batchId"`
}

func (UndoRenameRequest) ValidatePayload(payload []byte) error {
	return framework.ValidateRequestPayload[UndoRenameRequest](payload)
}

var undoRenameRequestRules = framework.NewRuleRegistry[UndoRenameRequest](
	framework.ForField(
		"batchId",
		func(request UndoRenameRequest) string { return request.BatchId },
		framework.MinLength(1, "BatchId must be at least 1 character."),
	),
)

func (request UndoRenameRequest) Validate() error {
	return undoRenameRequestRules.Validate(request)
}
